[package]
name = "printvars-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
printvars-core = { path = "../printvars-core" }
proc-macro2 = "1.0"
